export const SHOWHEADER = 'SHOWHEADER';
export const HIDEHEADER = 'HIDEHEADER';

export const STARTANIMATIONCHANGECHANGE = 'STARTANIMATIONCHANGECHANGE';

export const SHOWSTARTANIMATION = 'SHOWSTARTANIMATION';
export const HIDESTARTANIMATION = 'HIDESTARTANIMATION';

export const SHOWSTARTCLOSE = 'SHOWSTARTCLOSE';
export const HIDESTARTCLOSE = 'HIDESTARTCLOSE';


